spring:
  application:
    name: music-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/lopply
    username: postgres
    password: test
    initialization-mode: always

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8084

grpc:
  port: 1232