CREATE TABLE artist (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      uuid UUID NOT NULL UNIQUE,
                                      name VARCHAR(255) NOT NULL,
    bio TEXT,
    country VARCHAR(100)
    );

CREATE TABLE album (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uuid UUID NOT NULL UNIQUE,
                                     title VARCHAR(255) NOT NULL,
    artist_id BIGINT NOT NULL,
    release_date DATE,
    FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE CASCADE
    );

CREATE TABLE genre (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uuid UUID NOT NULL UNIQUE,
                                     name VARCHAR(100) UNIQUE NOT NULL
    );

CREATE TABLE music (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255) NOT NULL,
                                     uuid UUID NOT NULL UNIQUE,
                                     album_id BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    duration INT,
    language VARCHAR(50),
    FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE,
    FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre(id) ON DELETE CASCADE
    );
